#http:
#  port: 8080
#  adminPort: 8081

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: pulkit19

  # the JDBC URL
  #dropwizarddb should be replaced with the db name
  url: jdbc:mysql://172.17.0.2:3306/mysql #when running for docker
#  url: jdbc:mysql://localhost:3306/mysql #when running on localIde

swagger:
  resourcePackage: com.dropwizard.service.resource
