#http:
#  port: 8080
#  adminPort: 8081

database:
  # the name of your JDBC driver
  driverClass: org.mariadb.jdbc.Driver

  # the username
  user: root

  # the password
  password: pulkit19

  # the JDBC URL
  #dropwizarddb should be replaced with the db name
  url: jdbc:mariadb://[::1]:3306/mysql

swagger:
  resourcePackage: com.dropwizard.service.resource
